# handlers file for ansible-nagios_server

- name: restart apache2 server
  service: 
     name: apache2
     state: restarted
     enabled: yes

- name: start nagios server
  service:
      name: nagios
      state: started

- name: restart nagios-server
  service:
     name: nagios 
     state: restarted 

